version: '3.1'

networks:
  kafka:
    driver: bridge
  application:
    driver: bridge

services:
  zookeeper:
    build: ./zookeeper
    networks:
      - kafka

  kafka:
    build: ./kafka
    networks:
      - kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"

  producer:
    build: ./ruby-kafka-producer
    networks:
      - kafka
    depends_on:
      - kafka
    volumes:
      - "./LFS:/LFS"
    environment:
      KAFKA_URL: "kafka"
      KAFKA_TOPIC_NAME: "new-files"
      KAFKA_PRODUCER_VERBOSE: "false"
      LISTEN_DIR: "/LFS"

  db:
    image: postgres
    networks:
      - application
    volumes:
      - ./rails-consumer-app/tmp/postgresql/data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: "postgres"

  app:
    build: ./rails-consumer-app
    networks:
      - application
    depends_on:
      - db
    volumes:
      - ./rails-consumer-app:/app
    ports: 
      - "3000:3000"
    environment:
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"

  racecar:
    build: ./rails-consumer-app
    command: 'bundle exec racecar NewFileListenerConsumer'
    networks:
      - kafka
      - application
    volumes:
      - ./rails-consumer-app:/app
    environment:
      KAFKA_URL: "kafka"
      KAFKA_TOPIC_NAME: "new-files"
      DATABASE_HOST: "db"
      DATABASE_USERNAME: "postgres"
      DATABASE_PASSWORD: "postgres"
    depends_on:
      - kafka
      - db
