version: '3.1'

networks:
  baum-kafka:
    driver: bridge

services:
  zookeeper:
    build: ./zookeeper
    ports:
      - '2181:2181'
    networks:
      - baum-kafka

  kafka:
    build: ./kafka
    networks:
      - baum-kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092

  producer:
    build: ./ruby-kafka-producer
    networks:
      - baum-kafka
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - "./LFS:/LFS"
    environment:
      - KAFKA_URL=kafka
      - KAFKA_TOPIC_NAME=timer-log
      - KAFKA_PRODUCER_VERBOSE=false
      - LISTEN_DIR=/LFS

  consumer:
    build: ./ruby-kafka-consumer
    networks:
      - baum-kafka
    depends_on:
      - zookeeper
      - kafka
    environment:
      - KAFKA_URL=kafka
      - KAFKA_GROUP_ID=ruby-consumer
      - KAFKA_TOPIC_NAME=timer-log
      - KAFKA_CONSUMER_VERBOSE=false
